### ISSUE TITLE
[Bug]: Nightvision flashing constantly

### ISSUE THREAD

**Issue by aerialspring** [TeamLapen/Vampirism#1047]
### Minecraft Version

1.18.x

### Forge Version

36.0.75

### Vampirism Version

1.8.0-beta.3

### Modpack

https://www.curseforge.com/minecraft/modpacks/scumpack-x-for-1-18-1

### Singleplayer/Multiplayer

Both

### What happened?

After unlocking nightvision as a vampire, the screen flashes constantly. 

### Reproduce steps

1. Load world.
2. Level up as vampire
3. Unlock nightvision
4. wait til night time

**Comment by Cheaterpaul** [comment]
When nightvision is enabled we add the nightvision effect every second. 

The flashing could be caused by items or other mods that remove/clear some effects or specifically night vision.

It testet is shortly with the modpack and could not reproduce this.  Which might indicate that the behavior only occurs under specific states. So you know anything that could remove the effect?

You can switch the vampire night vision by pressing "N" to disable the flashing

**Comment by Cheaterpaul** [comment]
Are you using any shader. And if true does the flashing stopps without shaders?

**Comment by aerialspring** [comment]
No shaders. Using "n" to disable night vision doesn't seem to work either.

**Comment by aerialspring** [comment]
Hi there! I have finally tracked this issue down to Project MMO's underwater night vision perk as it was affecting other night vision sources as well. Disabling that perk completely fixed the issue.

Thank you!

**Comment by IchigoGames** [comment]
oh thats what that is i had the same issue
