### ISSUE TITLE
1.19 Update

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Vampirism#1102]
TODOS:
- [x] update to latest forge version
- [x] check todos. Some things must be checked
- [x] add vampire forest (works on first world load, but not on loading a created world)
- [x] check biome data modification
- [x] vampire spawning somehow do not spawn in other biomes (spawn predicate returns false)
- [x] add jei integration (jei needs a forge update and updated integration)
- [x] add guide api integration (guide api needs a forge update)
- [x] weapon table recipes with potions (swiftness armor)
- [x] test

**Comment by maxanier** [comment]
Neat.
Questions:
- Why Java18? Forge seems to be using Java17
- VampirismRegistries in API seems odd. Can we at least make the public fields final? Isn't there some sort of preferred way for addon mods to obtain registries (optional) registries

**Comment by Cheaterpaul** [comment]
> Why Java18? Forge seems to be using Java17

Yeah, mixin had some problem with Java 17, but now it is working.

> VampirismRegistries in API seems odd. Can we at least make the public fields final? Isn't there some sort of preferred way for addon mods to obtain registries (optional) registries

I moved the registries and deferred registries back to ModRegistries and only kept the RegistryKeys and default forge registry supplier in VampirismRegistries. (Some supplier are required for DefaultSkill/DefaultAction, but this may be solved on another way)  

(pushing later today)

**Comment by Cheaterpaul** [comment]
We can also think about replacing RefinementSets with Refinement Tags.

**Comment by JDBS** [comment]
> Neat. Questions:
> 
> * Why Java18? Forge seems to be using Java17

About Java 18, all i could say is that [Java 17 will be LTS until September 2026](https://www.oracle.com/java/technologies/java-se-support-roadmap.html).
 
Surelly mojang and Forge will keep Java 17 for so long (Java 18 will not recieve fixes, optimizations or security updates).
Middle versions are unstable versions. Probably you already know about Java LTS versions. Otherwise hope you find this information helpful.

Anyway, thank you for keeping maintenance over this mod.

**Comment by Cheaterpaul** [comment]
First release was released
