### ISSUE TITLE
[Bug]: Regeneration effect is not applied for Regeneration Action

### ISSUE THREAD

**Issue by numerobis21** [TeamLapen/Vampirism#1122]
### Minecraft Version

1.18.x

### Forge Version

40.1.60

### Vampirism Version

1.8.5

### Singleplayer/Multiplayer

Server

### What happened?

When using the Regeneration Skill, I get the "Thirst" status, but not the "Regeneration" Status.
The message "You are not allowed to use this effect yet" appears.
I feel like this started to happen from the point I had to log out while resurrecting (I was alive when reconnecting), but I'm not sure if that's what caused it

### Other relevant mods

Collection of Singiro 1.0

**Comment by Cheaterpaul** [comment]
This seems like some mod does not allow the usage of the regeneration effect under your current situation.

This is likely caused by Collection of Singiro or another origins mod, that does not allow this effect.

I would rather see this an incompatibility with some mod rather than a bug, maybe your origin simply does not allow that effect.

**Comment by Cheaterpaul** [comment]
Feel free to reopen the issue, if this bug is still present
