### ISSUE TITLE
[Feature]: Unique Textures for Armor of Swiftness

### ISSUE THREAD

**Issue by Inonedn** [TeamLapen/Vampirism#1123]
### What?

It’d be cool if Armor of Swiftness got retextures so they aren’t just retextures of Leather Armor with a few touchups, with a more reinforced lightweight look

### Mod experience

Currently the armor of swiftness texture is really old and doesn’t have much to stand out compared to Leather Armor besides being a slight retexture. A new texture would be nice

**Comment by Cheaterpaul** [comment]
That's exactly what we thought as well. Because of that the Armor of Swiftness was re-textured for the 1.9 version of Vampirism which is currently available for 1.16.

They will look like this:
![image](https://user-images.githubusercontent.com/17816456/185246192-179b64d9-0d30-4ecd-b6fc-82600c8bdd66.png)
