### ISSUE TITLE
[Feature]: Vampire ability improvements

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1158]
### What?

Ability selection has always felt a bit clunky - sometimes it doesn't register when you selected an item which can leave you in a risky situation (such as when sunscreen doesn't activate), and needing to circle select the same ability every time is cumbersome.  

My suggestion is to change the ability bar to work as such:  
- Hold the ability button to display the circle (current behaviour)
- Selecting an item marks it as the current ability, which is displayed next to the hotbar in a similar manner to the off-hand item
- Pressing the ability button without holding it uses the current ability
- Selecting a newly added "None" option would allow hiding the ability slot from the screen until an ability is selected (similar to how the off-hand slot is hidden when you don't have a shield equipped) - this could probably be combined with the current Cancel option, since it would no longer be activating abilities directly

This could of course be configurable in the actions menu to allow instant selection (current behaviour) for those who like it as it works right now.

For individual abilities, here are some changes I think may benefit them:
- Dark blood projectiles feel really underwhelming to use currently. One way to make them more engaging to play with could be to have the ability be a toggle which makes your left clicks launch bloody projectiles at the cost of giving thirst for a few seconds with each shot
- Teleport is in a really rough state currently - I think it should be more of a blink that sends you forward, but with a delay and visual/audible effects to go along with it, such as a blood trail. That way it would feel engaging to use while being predictable/counterable for other players
- Night vision... the toggleable easy mining tool. This may be better as a toggled option for slightly better vision in the dark while making light areas hard to look at, further fitting the "painful sunlight" aspect of vampirism without making spelunking a joke. Currently you're almost always better off with night vision over the entity radar mode just because of how powerful it is with no downsides
- I could write an entire page about bat form, but to keep it short; it feels like creative mode the moment you unlock it. One is able to travel too easily over long horizontal distances whereas bat form should probably be a tool for quick escapes and short-distance vertical travel. Perhaps the default travelling speed should be further reduced?

I hope some of these changes can be considered as they would greatly improve the playing experience as a vampire.
Thank you.

### Mod experience

It would greatly improve the dynamics of real-time gameplay, as you would no longer be forced to go through the ability selector and hope your abilities actually activate. Some abilities in general would become actually useable and PVP would benefit from the changes.

### Contributions

No, sorry. Happy to help tweak the default balance if requested though!

**Comment by MarioSMB** [comment]
As a sidenote, I do think dark blood projectiles should be part of a unique weapon for vampires rather than an ability, as it's essentially a weapon attack.

**Comment by maxanier** [comment]
Thank you for your suggestions. We have discussed them with the following results:

We agree that the action wheel can be a bit problematic, but your suggested alternative behavior is also a bit clunky. Activating a new ability requires more key presses and hence more time. Cheaterpaul has already reworked the current menu to behave bit better (coming with 1.10) and combined with the already available option to bind specific actions to specific keys should allow swift activation of those in a combat situation.

The dark blood projectile is probably not great atm, but if you bind it to some key, you can just use it along the way. The cooldown is not too long, I think.
So far we refrained from adding real magic blood items (unless you consider the vampire swords as such). Somehow I do not like the idea of a blood projectile throwing staff or similar.

The alternative teleport sounds great. #1165 

Night Vision could be more interesting, but a) it is intentional that there is no reason to turn it off (vampires must live in the dark, but should not suffer to much from this)  and b) from an implementation perspective it is to most reliable and mod compatible way to just use the vanilla night vision effect.

We agree that bat mode is a bit lame and a bit too "creative". Some or even many will not like changing this, but it is worth looking into #1166

Thank you again for this extensive feedback

**Comment by MarioSMB** [comment]
Thank you for the positive feedback, it's a breath of fresh air!

I'm glad to hear there are improvements coming to the action wheel. My suggestion mostly stems from games that implement a quick slot button, which is indeed a tad different to the goals of the action wheel. I look forward to seeing how it works in the future!

If anything comes to mind to improve the dark blood projectiles, I'll make a separate issue for them. I can understand not wanting to introduce blood magic, though it is a shame given the close ties vampires generally have to it.

I guess what bugs me most about night vision is that it makes the world fullbright which looks hideous, so I find myself just turning it on to cheese the caves while mining, and not much else.  
Perhaps it can be revisited someday in the form of a slight brightness boost or something, but I understand wanting to keep it compatible and stable. The option to disable it in configs will probably be good enough for me in the future though!

Thank you all for taking time to look over all this - apologies for putting forward so much at once!
