### ISSUE TITLE
[Feature]: Improvements to pie menu selection

### ISSUE THREAD

**Issue by Jackiecrazy** [TeamLapen/Vampirism#1205]
### What?

Currently it seems like the ability pie menu requires your mouse to actually land on one of the slices in order to use the ability. This is a little complicated in practice as I often don't actually see my cursor in this screen and thus have to rely on guesswork to cast each ability. It also makes casting difficult in the middle of combat when you don't have time to methodically move there. In practice this means I often forgo using abilities in combat altogether, which is a little unfortunate. A more lenient selection (such as interpreting selection even if they are beyond the slice, as long as they are in that quadrant of the screen) and showing the mouse on selection would really help with quick use.

### Mod experience

I think it'd improve usability by a lot.

### Contributions

I do [this](https://github.com/Jackiecrazy/WarDance/blob/1bed4ad93b0215f45f0c38bd64726db8d40f052d/src/main/java/jackiecrazy/wardance/client/screen/SkillCastScreen.java#L70-L84) in my mod, and it seems to be decently received.

**Comment by Cheaterpaul** [comment]
For the next feature update I reworked the pie menu https://github.com/TeamLapen/Vampirism/pull/1135.
The cursor is visible, but was required to land on the pies to select the action.

I now changed this, so that the mouse just needs to be in the quadrant of the action to count as selected. (With a minimum distance to the center of the screen)  5f3fc265f46e807368537cf3640afa48b383c720

This should make it much easier and quicker to select an action from the menu
