### ISSUE TITLE
/vampirism modifyMinionInventory does not account for spaces

### ISSUE THREAD

**Issue by lunofe** [TeamLapen/Vampirism#1209]
If a minion has a space in its name, it's not possible to select it, even with tab auto completion or quote marks.

![2023-04-30_20-23_1](https://user-images.githubusercontent.com/42828197/235370217-cb7aa70f-3465-4093-beb4-65449b753b1d.png)

![2023-04-30_20-27](https://user-images.githubusercontent.com/42828197/235370223-43a30a77-1c84-4dd3-9c71-b808cc66a6b2.png)

Using the unicode escape character works, but... eh.

![2023-04-30_20-25](https://user-images.githubusercontent.com/42828197/235370252-93e3a1b5-6550-4b05-a7e2-76d7a2d1c624.png)

**Comment by supermike1999** [comment]
![image](https://user-images.githubusercontent.com/106882130/235371888-6a21b095-7162-42f9-af21-420e7c2c4afe.png)
You can still access a Minion Inventory without using the Unicode if said minion has a space between the name. (Singleplayer)

Unsure if it works on the Vampirism server

**Comment by Cheaterpaul** [comment]
This will be fixed by adding quotes around the id if it contains spaces.

However, the functionality of the command is not effected. The command only requires the player name and the id of the minion (`supermike:0`), the name is only there for informational purposes.

`/vampirism modifyMinionInventory supermike:0` does the same as `/vampirism modifyMinionInventory supermike:0/Bob` given Bob is the minions name.

**Comment by Cheaterpaul** [comment]
implemented in cf0d45da for 1.16 and d5ac8901 ... 90dc1194 for 1.19+

See https://wiki.vampirism.dev/docs/wiki/commands#modify-minion-inventory for the new syntax
