### ISSUE TITLE
[Modcompat]: Vampirism X NostalgicTweaks Crash

### ISSUE THREAD

**Issue by guivnf** [TeamLapen/Vampirism#1218]
### Minecraft Version

1.18.x

### Forge Version

40.2.8

### Vampirism Version

1.8.8

### Incompatible mod

Nostalgic Tweaks

### Singleplayer/Multiplayer

Both

### What happened?

When i right-click the Altar of Inspiration from vampirism with a blood bottle, my game crashes

### Reproduce steps

1. get the two mods
2. get the altar of inspiration
3. get a blood bottle
4. right click the altar of inspiration with nostalgic tweaks installed
5. crash

### Relevant log output

```shell
https://mclo.gs/2vmZkKJ
```

**Comment by guivnf** [comment]
https://github.com/Adrenix/Nostalgic-Tweaks/issues/38

**Comment by guivnf** [comment]
Closing issue as this has been solved on Nostalgic Tweaks side.

**Comment by maxanier** [comment]
Thank you for reporting and nice that it is already fixed on Nostalgic Tweaks's side.

We will have a look if having `null` sounds is unexpected behavior

**Comment by Cheaterpaul** [comment]
Based on my findings, I can confirm that this is irrelevant for version 1.19.4+ because the FluidType#getSound is @Nullable and must be handled correctly. However, I have not tested versions 1.19 to 1.19.3.

n version 1.18.2, the corresponding method FluidAttributes#getFillSound is not annotated with @Nullable. However, that class is not annotated with @FieldsAndMethodsAreNonnullByDefault (at least from what I can gather). This lack of annotation provides no guarantee regarding nullability. It should be noted that my IDE did not give me a warning about nullability because there is no guarantee.

Apart from the annotations, both Vanilla and Forge treat the method as nullable.

Since it does not appear in later versions, I would recommend keeping it as is.
