### ISSUE TITLE
Some possible improvements

### ISSUE THREAD

**Issue by EpicCreeperHD** [TeamLapen/Vampirism#122]
So for the most part I and everyone else on my server love this mod. We've been having a large war between two of the larger factions, The Abbey of the Mortal Man (Vampire Hunters) and my Covenant of the Dark Curse (Vampires) and after having multiple battles between max level Vampires and Vampire Hunters, we've started to come up with a few ideas and notice a few problems (mainly with the lore of Vampires).
We would like to share some of these with you so that you may take them insight into what we feel might make the mod better.

Number 1:
The book and other text-based things in the mod are poorly written. There's a few grammar mistakes here and there, which is fine for the most part as we can easily fix it (we have a rewritten version with some better grammar and more detailed information), but the descriptions for some things are often quite vague. Like the realistic mode for example. We have no idea what it changes.

Number 2:
The Vampire Hunters seem to be prepared for the wrong job. It is said that the smell of garlic is strong enough to overwhelm that of a rotting corpse and thus is too strong for a Vampire to stand with their heightened sense of smell, and yet it is being used to kill them, which it does not. This isn't surprising as the media had often led us to believe so, but we think that a smart idea would be to change the properties of the garlic to make it more of a repellant that disorientates and deters Vampires rather than doing them harm, and instead would opt for silver to take that role. In the old stories of Vampire Hunting, silver, fire and the wooden steak were the most common weapons. Silver was said to burn the skin and sometimes paralyze lesser Vampires like they were being electrocuted. Fire was said to destroy the Vampire in mere seconds. The stories say that they suffer much worse burns than any mortal man and that their flesh turns to ash once it is dead.

We feel like these could be reflected in-game. With silver weapons being made availiable to Vampire Hunters as well as some alchemical fire-based weaponry.  If you decide to go through with these changes, we suggest that silver should hit Vampires much harder than the old iron stuff and have a small chance to stun them and disable their abilities. Real silver is heavier and softer than iron or steel, and should swing slower and have a lower durability to balance them. Fire should deal up to 4x normal damage that scales up and down with level (to make it really scary). If you need any ideas about fire weaponry, look at the class videos of Nosgoth for the Alchemist. With that in mind, perhaps watch them all. That game had some very nice anti-vampire gear that could act as some good suggestions.
I'll provide a link to the Alchemist's video: 
https://www.youtube.com/watch?v=L2Vty5V-810

Number 3: 
Some vampire mechanics feel a bit off. Mainly the feeding. People have commented on the current feeding system and would like to see some changes, the first being made to the way that a vampire feeds. Rather than being an instant thing, it should be a slow drain over time. Let's say 5 seconds for a full drain that would kill a villager (and/or possibly turn them). Another suggested idea would be a "blood meter" on the side of the screen that would fill if your health and hunger were both full after feeding. This meter will be drained to heal the player and restore their hunger when lost and should last about 20 minutes from full at all levels before it is completely empty. Higher level vampires should still drain hunger faster, but have a larger blood meter and get more blood from feeding to compensate so that at any level one villager death will suffice (as long as they dont need to fight). Vampire abilities should also drain the blood bar to be used. But this should be a fixed value that only changes if the ability is improved somehow. This means that high-level vampires can use their abilites more in between feeding, but still have to suffer the cooldown whereas low-level vampires can only use it once or twice. This would also be a bit more of an encouragement to take blood bottles with you...

We'll likely clean this up and add to it. But this is really just a generalised bit of feedback from our server. We can understand if this seems a bit too much or not appealing in any way. It's just to really give you some of our thoughts.

Thanks
-EpicCreeper and Co.

**Comment by maxanier** [comment]
Thanks for your extensive feedback again. Happy to hear that you love this mod :)
Number 1:
There are two reasons for that: I'm German and my English is ok, but far from perfect and I don't like writing the descriptions (especially the guide book), because it takes lots of time.
If you wan't to you can try to fix some of the texts, so others can enjoy good English and I can see what I did wrong. (It also sounds like you have already done this for yourself).
Maybe you want to create a pull-request here (preferred) or send me the relevant files per mail. The most interesting files are [main_language_file](https://github.com/TeamLapen/Vampirism/blob/master/src/main/resources/assets/vampirism/lang/en_US.lang) (contains most strings), the [guide_book_file](https://github.com/TeamLapen/Vampirism/blob/master/src/main/resources/assets/vampirismguide/lang/en_US.lang) and anything [here](https://github.com/TeamLapen/Vampirism/tree/master/src/main/java/de/teamlapen/vampirism/config) (descriptions in the config and balance files).

(Realism mode is a desultory concept, that makes a few things "more realistic" e.g. entities do not turn instantly but also get the sanguinare vampirism effect (shorter version).

Number 2: 
As usual it is quite hard to get all the different lores and peoples opinions together while not forgetting about balance, gameplay and feasibility (in MC).
All that sounds reasonable and cool (and I already thought about adding silver), but there are quite a few of good ideas out there. But if I decide to change the current "behavior" I might actually go with this, because it sounds well thought out.

Number 3: 
A non-instant system sounds better, but it is quite hard to implement (at least without a blood meter).
But I'm not sure about "blood meter". It is definitively quite a fundamental change, so it is either to late (1.0.0 is already released) or the early (something like 2.0 is far away).
I will keep this in mind, maybe it will end up in the mod, maybe not.

**Comment by maxanier** [comment]
Since it is hard to manage an issue with different suggestions, I've split them up and closed this one, feel free to take a look at them and comment if you have more to say (especially #132, there is currently a forum post asking about feedback)
