### ISSUE TITLE
Ticking entity server crash

### ISSUE THREAD

**Issue by sharkck** [TeamLapen/Vampirism#140]
One of my players hit a vampire (in self defense!) and it crashed the server.  Here is the crash log:
[crash-2017-01-18_14.10.54-server.txt](https://github.com/TeamLapen/Vampirism/files/714814/crash-2017-01-18_14.10.54-server.txt)

Server log: 
[fml-server-3.txt](https://github.com/TeamLapen/Vampirism/files/714816/fml-server-3.txt)

Server info: 
Forge version 2215
Vampirism version 1.0.3

**Comment by maxanier** [comment]
Thanks for the report and the included logs.
I've an idea what might be causing this crash, but with just Vampirism installed it should be impossible, so maybe another mod interferes. 
Does this happen frequently? 
If so, I will try fixing it, otherwise it is probably just bad luck/timing with another mod.

Also could you try hitting an advanced vampire multiple times (maybe 10) and see if the server crashes? Thx

**Comment by maxanier** [comment]
Is this still an issue? If so could you please answer the questions above, otherwise I will close this issue. Thx

**Comment by maxanier** [comment]
Closing since I did not receive any answer. If this still exists and you are willing to provide some more information, reopen this issue.
