### ISSUE TITLE
[Bug]: Milk Bucket no cancel vampiris sanguinare

### ISSUE THREAD

**Issue by ALPHESSA** [TeamLapen/Vampirism#1417]
### Minecraft Version

1.21.x

### (Neo)Forge Version

21.1.54

### Vampirism Version

1.21-1.10.0... (latest version)

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I drank milk bucket to cancel Sanguinare Vampiris but it would not cancel. I have tried it twice in survival, and drank over 10 milk buckets or so. I only waited the full 15 minutes once, and yes, I turned into a vampire. I even tried it on a world that only had the Vampirism mod.

### Reproduce steps

1. Load survival single player world
2. Get Sanguinare Vampiris by bite or fangs
3. Drink more milk than humanly possible
4. Wait till timer is up and become a vampire with an incredible calcium intake

### Other relevant mods

First found the bug in gameplay with Werewolves mod and Vampirism, plus an optimizing mod. Replicated in game with just Vampirism mod.

**Comment by maxanier** [comment]
Can confirm. Thank you for reporting.

@Cheaterpaul 
It is intentional that sanguinare can only be cured by garlic now?
If not, in https://github.com/TeamLapen/Vampirism/blob/3eeabc64068c1d02e8705bbe4dd2d082bbaa6d2e/src/main/java/de/teamlapen/vampirism/effects/SanguinareEffect.java#L57 the call to the super method is missing.

Also it seems the garlic cure does not work, since you cannot eat garlic. Or do I have to do something else?
Affects both Neoforge branches (1.20.6/1.21)

**Edit**: So the garlic bread is supposed to cure it, but only hunter players can eat it.

**Comment by maxanier** [comment]
Ok, I have removed the IFactionExclusive from the garlic bread, but made sure Vampire throw it away when holding it.

Still probably want to readd milk.
