### ISSUE TITLE
Translation / PT-BR

### ISSUE THREAD

**Issue by evernife** [TeamLapen/Vampirism#16]
Hello friend, i am a brazilian developer, i want to translate your mod because i found it really interesting.

If you want me to translate, just give me the lang files. I will be really grateful to help. ^^

Translate for Portuguese (Brazilian)

**Comment by maxanier** [comment]
You can find the lang files under in this repository in the [resource folder](https://github.com/TeamLapen/Vampirism/tree/master/src/main/resources/assets/vampirism/lang), either make a pull request or send us a pastebin or so of the translation.
Maybe you want to wait 10 days or so, since we will probably add serveral new texts.
Thanks in advance :)

**Comment by evernife** [comment]
I will wait so, i am glad to help. Ty dude. ^^
