### ISSUE TITLE
Sunscreen beacon usage

### ISSUE THREAD

**Issue by LemADEC** [TeamLapen/Vampirism#164]
## Versions
- Minecraft: 1.10.2
- Forge: n/a
- Vampirism: 1.10.2-1.1.0-beta.2

## Issue Description
Sunscreen beacon is missing wiki page or a better tooltip without resorting to reading through the source code.
We could use a range configuration for it so we don't have to spam them all around protected areas.

## Reproduce Steps
n/a

## Additional Information
n/a

**Comment by maxanier** [comment]
The guide book should give a short overview of the function.
Since I do not have time to keep a wiki up-to-data, anything else has to be found out by testing or youtube.

But I've added a configuration option for the radius (balance_hunter_skills/garlic_beacon...), although the standard configuration results in quite a large area already:
![img](https://picload.org/image/rcpiocii/2017-05-06_19.09.44.png "Demo")
Stone border: 3x3 Chunks Enhanced version

The "weak" version which is only available in creative and only prevents vampires from spawning, affects an even larger area 5x5 chunks.

**Comment by LemADEC** [comment]
I was talking about the Suncreen beacon but you're talking about the Garlic beacon, I'm a bit confused.

We use the Suncreen beacon to protect our spawn which is at least 10x10 chunks, up to 16x16. Since calls to getEntitiesWithinAABB() are fairly CPU intensive, having a single beacon would save us some resources.

To me a simple tooltip update would be good documentation, something like:
https://github.com/TeamLapen/Vampirism/blob/1.10-1.2/src/main/java/de/teamlapen/vampirism/blocks/BlockSunscreenBeacon.java#L32
change
"Intended to be used by server admins"
to
"Creative only. Give sunscreen to vampire players in a 32 blocks radius, from 0 to world height."

**Comment by maxanier** [comment]
Damn, reading is hard :man_facepalming: , sorry.
Will add that right away.

**Comment by maxanier** [comment]
Alright added config option and tooltip. A ingame configuration per beacon would probably be best, but don't have time to implement that.

Also moved from World#getEntitiesWithinAABB to World#getPlayers which should be far less CPU intensive, since it only loops through the loaded players, not sure why I even used the other one in the first place.

Thanks for the feedback
