### ISSUE TITLE
[SpongeForge][server][1.10.2] you do not have permission to use this command but there's no permission node

### ISSUE THREAD

**Issue by macks2008** [TeamLapen/Vampirism#166]
## Versions
- Minecraft:                 1.10.2
- Forge:                       2281
- Vampirism:                not latest :P? I'm kidding. The exact version according to the file name is Vampirism-1.10.2-1.1.0-beta.1                             
- (SpongeForge)          beta-2300
- (LuckPerms)              3.1.26

## Issue Description
"You do not have permission to use this command" when I'm in game and try to run "/vampirism resetbalance", and I can't even run "/vampirism fang" (whatever it does) from the console. Naturally, since I'm running a permission plug-in, I tried to find a relevant permission node so I could give myself permission to it... except there doesn't seem to be a remotely relevant node ANYWHERE in the permission tree. I even had luckPerms dump the entire tree [here](https://gist.github.com/anonymous/5f96c070ecd65d6019aa9a3cd31735fd) but still couldn't find it such a node

## Reproduce Steps
not sure. I could give you my server instance? IDK.

**Comment by maxanier** [comment]
For some reason (probably because the vanilla permission system is not very configurable) I made Vampirism's command check permissions in another way than usual. Thereby a permission plugin can not allow or disallow the usage.
Running "/vampirism resetbalance" should work in the console ("/vampirism fang" should not work in the console as you need to be a player for that).

I will consider reworking the permission system in Version 1.2 to improve this.

**Comment by maxanier** [comment]
I hope this worked.

In Version 1.2 the command system is changed and should work together with a permission plugin.
