### ISSUE TITLE
WorldEdit Compatibility

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#178]
## Versions
- Minecraft:         1.11.2           
- Forge:                      forge-1.11.2-13.20.0.2310 
- Vampirism:                 Vampirism-1.11.2-1.2.0-alpha+05-26-13-10                            

## Issue Description
When I try to use codes like for blocks such as Cursed Earth, it keeps on telling me it is invalid.

## Reproduce Steps

-Install WorldEdit
-Do //wand
-Select two positions with left and right click of the mouse
-Do //set 4099 or //set vampirism:cursed_earth; you can even try the other commands that come with WorldEdit, you will get the same result.

## Additional Information

WorldEdit Version: worldedit-forge-mc1.11-6.1.6-dist

**Comment by maxanier** [comment]
I don't have time to look into this right now, I will take a look in a week or so.

But I don't think this is caused by Vampirism, as Cursed Earth is a very simple (vanilla like) block. Did you try it with other modded blocks (from other mods)? 
Also the world edit version for sponge works just fine.

In case you do not find another solution until next week, can you upload you fml-client-latest.log after trying to set the blocks?

**Comment by maxanier** [comment]
I took a look, but WorldEdit seems to not care about modded blocks. However, it is possible to set them via id(:meta).
If you use /info and right-click one of vampirism blocks it should output the correct id.
