### ISSUE TITLE
Can't load up world

### ISSUE THREAD

**Issue by PoofFrags** [TeamLapen/Vampirism#219]
Whenever I load up my world, the game just crashes.
I don't know what is causing the issue but I just cant load up or create a world because before it even loads in the game crashes
BTW its in 1.11.2 but idk how to add Labels

**Comment by maxanier** [comment]
Pls provide I need more information. Otherwise there is no way I can fix this.

Pls fill in the Vampirism version and provide a crash report
(Find the Minecraft log file: If you use the standard Minecraft launcher, the interesting logfile is .minecraft/logs/fml-client-latest.txt. (How to find the .minecraft folder). In case you have a server, the interesting log file should be logs/fml-server-latest.txt. If you use another launcher, it might have a function to easily upload or locate log files.)

**Comment by maxanier** [comment]
Closing since no response
