### ISSUE TITLE
Can't fly in bat mode - Totem Essentials

### ISSUE THREAD

**Issue by soulsrocks13** [TeamLapen/Vampirism#230]
## Versions
- Minecraft: 1.12.2                   
- Forge:  1.12.2                     
- Vampirism: 1.12.1                                            

## Issue Description
I can't seem to be able to fly as a bat and all I can do is hop around? I also don't have the vampire guide book

**Comment by maxanier** [comment]
Do you have any flight/cheat related mods installed?

For the GuideBook you need to install GuideAPI https://minecraft.curseforge.com/projects/guide-api

**Comment by 63502** [comment]
I have the same problem, but I have no other mods that add creative style flight as far as I know.
I have my mod list here just in case it helps, or you see something I missed.

[Mod List](https://gist.github.com/63502/ae98a471ecc4d5ce9783b595b16c8016)

**Comment by maxanier** [comment]
That are a lot of mods, I don't have the time to go though check them all.

Can you confirm that this issue does not appear with only Forge, Vampirism, installed?

If so try temporary removing colytra, attributefix, randomtweaks.

If the issue is still present, the only idea I have is to remove all mods and add them back one by one (or maybe 5 at once) until the issue appears

**Comment by 63502** [comment]
I'll make sure to test it. I don't have that much spare time right now though, so unless I'm lucky, I may not have the chance for a couple days.

**Comment by 63502** [comment]
Scratch that statement I just made. XD

I made a lucky guess, and I found the offending mod. Turns out it was totem essentials. Totem essentials adds a couple of items called the totem of phasing and the ensouled totem of phasing. Both of them allow the player some form of flight while in their inventory, and both allow the player to clip through blocks, just like a vex. I would hazard a guess that there is some form of conflict between how both vampirism and totem essentials(and possibly other mods) give flight to players. I don't have the ability to find out which mod this conflict originates from though. If this is a totem essentials issue, please do tell me so I can post it on that mod's issues section instead.

**Comment by maxanier** [comment]
Many thanks for looking into this, I have identified the problem and created a issue at their repository.

**Comment by 63502** [comment]
Cool, glad I could help. :)

**Comment by IceMetalPunk** [comment]
Thanks for noticing this issue with Totem Essentials; I've just released a patch version 1.0.2 for Totem Essentials that should fix this incompatibility :)

**Comment by maxanier** [comment]
@soulsrocks13 If you have a different problem as 63502, pls create a new issue with a more detailed description
