### ISSUE TITLE
[1.10] Causes crash due to conflict with real terrain generation mod and Vampirism

### ISSUE THREAD

**Issue by demfels** [TeamLapen/Vampirism#234]
## Versions
- Minecraft:   1.10                 
- Forge:  12.18.3.2422          
- Vampirism:        1.2.3                                     

Occurs during loading game (not world).

**Crash report here: https://pastebin.com/7qj3cX8B**

exception from Realistic Terrain Generation (RTG)
Caused by: java.lang.ExceptionInInitializerError
	at rtg.world.biome.realistic.vampirism.RealisticBiomeVAMPBase.addBiomes(RealisticBiomeVAMPBase.java:61)

**Comment by maxanier** [comment]
This is caused by the block renaming in the latest 1.10 version (to match the naming conventions enforced in 1.11).

I cannot do anything about this. Not sure if the RTG is willing to release another update to their 1.10 version.
Easiest solution would be to use Vampirism 1.1 or update to MC1.11 (even though there seems to be no support for the Vampire Forest in RTG 1.11 yet.

I will create an issue on their repo.

**Comment by maxanier** [comment]
Oh, there already you already created one there https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1225
Please crosslink such things in the future to avoid developers from spending time on things that have already been investigated

**Comment by demfels** [comment]
First off, thank you both (RTG and Max) to looking at this so quick.  I didn't anticipate a response so quickly.  My bad on the cross link.  I didn't know I could do that.

I'm not moving to MC 1.11.  I run a modpack and server.  I'm considering adding in Vampirism to my modpack by request of some users.   I'm going to test using version 1.1.2 of your mod and see if that works out okay.  If there are concerns with using 1.1.2 let me know.

**Comment by maxanier** [comment]
As long has you did not load the map with Vampirism 1.2.x before there should be no issue with using 1.1.x (might contain a few minor bugs that are fixed in 1.2).
