### ISSUE TITLE
Small problem with Project E Body stone

### ISSUE THREAD

**Issue by Caopr** [TeamLapen/Vampirism#237]
## Versions
- Minecraft: 1.12.2                    
- Forge: 14.23.0.2531                      
- Vampirism: 1.3.2                                            

## Issue Description
The body stone from Project E is supposed to restore hunger in exchange for EMC. it soaks up emc but wont restore vampire hunger. Probably due to how vampire hunger differs?

just a suggestion to try making a method for things like this from other mods affect vampires. Reliquaries charms are able to take hunger just fine.

## Reproduce Steps

Just activate a bodystone with energy in inventory

## Additional Information

Extra Suggestion: make a way to automate blood gathering from animals? stack-able blood vials?

p.s. I made a vampire hunter spawner with Soul shards TOW. And the hunters that come out use crossbows unlike wild ones. which i figured might be good info to give.

**Comment by maxanier** [comment]
Thank you for reporting.
It is indeed caused by Vampirism not using the standard food stats but its own blood stats.
Unfortunately, there does not seem to be an easy solution for this. It would probably require one of the two mods to add the other's API to implement some integration. 
But I don't think it is worth it. If you really really want it you can create an issue over at their repository so we can figure out the best solution together.

I guess there are more incompatibilities with other mods that do something related with food. Consumption should usually work fine, but feeding is difficult, because Vampirism can't really figure out if the player is fed by bread (which does not help Vampires) or by some other magic way.

That is strange, some of the wild vampire hunters should use crossbows as well. The ones from the spawner should have random equipment. I will look into that.
