### ISSUE TITLE
Rework villages. Allow players to take over villages (hunter/vampire)

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#241]
Description: https://gist.github.com/maxanier/a2cacf5294c4cfe02ab131f59e7199c2#file-description-md

**Comment by maxanier** [comment]
Very basic system (currently cheat only) implemented in 8d18718c06bc8e6f4277ee7c3937157f3a672160. Likely to be extended

**Comment by AlbertoJVD** [comment]
Maxanier: Moved here [http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2756555-vampirism-become-a-vampire-now-with-optional-mca?comment=301](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2756555-vampirism-become-a-vampire-now-with-optional-mca?comment=301)

**Comment by AlbertoJVD** [comment]
Villages will eventually be taken over by the opposite faction:

Only if structure not refilled? 
**With my suggestion, structure not refilled with blood/holy water would take away the area of effect buff and allow the enemy close enough for it to break its link and then the core to control village in their favor.**

**Extra: Now that I think of a liquid source for hunters compared to blood: Maybe the controlling structure could be a simple fountain with the specified liquid! And there could be 3 ranks to the fountain, with each allowing new buffs to the controlling faction. These fountains would need the player to upgrade them like leveling altars, in order to provide a new rank of control/buffs.** 

Small chance if player not near: **I don't necessarily like this. Raids and attacks are fine but in a complex village control system this could be a big loss.**

Just a simulation in background and e.g. applied once chunk loaded? **If we don't have them work in the background is better. Having the player present during these control attacks would be better.**

**Comment by AlbertoJVD** [comment]
Small raids might happen if the player is nearby:

A small number of the opposite faction attack, but should not cause much permanent damage
I like this idea, we could also have a local chat notification if close enough with a specific text for each faction, example:

Hunters: 
--"A nearby village is under vampire attack!"(If there is a vampire raid on hunter controlled village)
--"A nearby village may need assistance."(If its a neutral village that can be controlled by the hunter player).

Vampire: 
--"A nearby village wrecks with the scent of garlic!"(If hunters are raiding a vampire controlled village)
--"A nearby village sounds peaceful" (If its a neutral village ready to be controlled)

**Comment by AlbertoJVD** [comment]
Villages are controlled by a block or block structure
Block has to be refilled every now and then with blood/garlic 

-Can we have it draw blood from the blood tanks if placed directly next to it? This would help greatly with handling multiple villages. Maybe even have a timer of how much you have left before blood runs out?

If not, loose control or disable effects or higher chance of successful take overs? 

-Yes

**Comment by maxanier** [comment]
Thank you for your suggestions :) but I think it is better to do the discussion on the forums and only use this for implementation specific notes. Keeps the discussion in one place and this thread more clear.

Edit. Moved your comments to the forums

**Comment by maxanier** [comment]
This should also include a completely rewritten spawning systems for hunters and villagers.
Calculating the number based on doors, limiting it to a maximum number per village and per day does not seem to work out at all.

Possible reasons why the current system is not working:
- Hunters somehow die immediately
- Hunters are somehow moved out of the recognized village area
- Village area is somehow reduced
- Somehow one acmtual (blocks) village is recognized as two separate villages in "code"
- Other mods do strange things

If we were to use the "totem" as integral part of the concept we could use it to keep track of spawned and alive hunters. Furthermore, we should consider area and villager count in addition to number of doors. We should also think about where exactly we want to spawn the entities and consider spawn preventing blocks
Last but not least, any logging should be limited to a single print out or only done if village debug mode is enabled.

**Comment by maxanier** [comment]
Should also try to keep memory footprint low by caching bounding boxes, avoid creating unnecessary lists (of undefined sizes) [Sometimes we don't really need an actual list, counting certain elements, or using one of googles Filtered lists should suffice]
We should also make sure we are not preventing chunk unloading and  villages in unloaded chunks are actually unloaded

**Comment by maxanier** [comment]
Closed with #386
