### ISSUE TITLE
Vampire Hunters not being mad at you for being a Vampire.

### ISSUE THREAD

**Issue by KingEdward9830** [TeamLapen/Vampirism#245]
## Versions
- Minecraft:  1.12.2                  
- Forge:  14.23.0.2529(note: I will update Forge later today)                     
- Vampirism:  1.3.2                                           

## Issue Description
Vampire Hunters are not immediately hostile to Vampire players or mobs, but rather will only attack if provoked. The same does NOT hold true for Vampires attacking human players.

## Reproduce Steps
1. Be a vampire
2. Go near Hunter NPCs in survival mode
3. Notice how passive they are
4. Go back to being human
5. Go near Vampire NPCs in survival
6. Get rekt cause they're still out for your blood!

## Additional Information
My Forge is outdated and I know it, I will test again later today with the latest recommended Forge version. Just wanted to get this to you in case it's actually a problem with the mod.

**Comment by maxanier** [comment]
Thank you very much for reporting.

Can confirm this bug. The (normal) hunters should attack you once you reload the map. Advanced hunters are apparently completely broken.
Will be fixed in the next alpha and I will probably also push a hotfix for the 1.3 version.

Almost sad that nobody else has reported it before, the bug has been there for quite some time now.

**Comment by maxanier** [comment]
Fix has be released https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2506565
