### ISSUE TITLE
Sleep Percentage doesn't take effect

### ISSUE THREAD

**Issue by flamechair** [TeamLapen/Vampirism#256]
## Versions
- Minecraft:      1.12.2              
- Forge:            14.23.1.25555           
- Vampirism:    1.3.6                                         

## Issue Description
Vampirism sleep config is set to 50%, but when 2/3 players sleep in a coffin, it doesn't trigger night. When the 1 person not sleeping in a coffin logs outs, it immediately changes to night

## Steps to reproduce
1. Set config to:
```   
I:coffin_sleep_percantage=50
```
2. Get 3 vampire players
3. Have 2 sleep in coffins
4. Notice that it doesn't change to night
5. Have the 1 vampire not sleeping log out
6. Notice that it immediately changes to night

## Additional Information
1. I do have morpheus installed, and it is set to 50% for day as well, I doubt it conflicts with this. But it is worth mentioning.
2. Also I noticed there is a typo in the config key `coffin_sleep_percantage` vs `coffin_sleep_percentage`

**Comment by maxanier** [comment]
Strange, someone confirmed it was working in #227, but I think this wasn't possible, because I messed up.

I fixed and tested it with 1 player sleeping and 1 player awake and 50% and it works now. Let me know if there are issues with different number of players or settings.

Can't do anything about the typo as it would break existing configs
