### ISSUE TITLE
Animals turn into vampires randomly! O.o?

### ISSUE THREAD

**Issue by Plaah007** [TeamLapen/Vampirism#257]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.1.2562                      
- Vampirism: 1.3.5                                            

## Issue Description
Animals turn into vampires randomly without being bitten by a vampire.
Can't have animal farm when they suddenly turn into vampire versions and attack other animals.
I have used name tag on the animals.

## Reproduce Steps
Leave animals in a 5x3x5 closed room that is lit.

**Comment by flamechair** [comment]
This might be related to: #249 

The bounding box of the bite radius was a little high, he reduced it. Hasn't been released yet though.

**Comment by maxanier** [comment]
It should be impossible to turn without being bitten.

As iamtpage mentioned, vampires might be (or have been) able to bite through fences or through corner blocks.

But you are saying to enclosed them within solid blocks? That is strange, I will have a look, but #249 would probably have fixed that issue as well.

**Comment by Plaah007** [comment]
Glass pane solid? Then yes.

![2018-01-06_20 58 17](https://user-images.githubusercontent.com/34899446/34642953-8a826348-f324-11e7-8ee4-c1810818b9df.png)

 Light levels 
![2018-01-06_21 01 39](https://user-images.githubusercontent.com/34899446/34642970-d17437c2-f324-11e7-8af6-2a7efef39809.png)

Inside my base is also 100% lit so there's no spawn points for mobs and they can't get to the glass pane side at all.

**Comment by flamechair** [comment]
Glass panes are solid, but due to bounding boxes (until the new update is released) if an animal is directly against it, the vampire would be able to bite it through the glass

**Comment by flamechair** [comment]
Try a solid glass block, not a glass pane

**Comment by Plaah007** [comment]
I tried putting two extra layers of blocks on the stone brick wall and there hasn't been any vampire animals since then. So it seems like they got bitten trough the stone bricks.

**Comment by maxanier** [comment]
Ok, the bite algorithm is indeed a little bit messy/inconsistent in v1.3.5, so it might have been possible for vampires to bite through stone walls if they happen to stand next to a wall with entities behind.
After the adjustments made for #249 and here, the behaviour is still slightly inconsistent, but the remaining issues should be ok:
- Blocks thicker than half a block as well as any non see through block should prevent entities from being bitten.
- One layer of fences is not enough. Vampires won't actively try to reach any entity inside, but if they happen to stand very close they can bite the entities (this makes more or less sense as discussed in #249)
- Glass panes may not be enough. Vampires won't actively try to reach any entity inside, but it is not guaranteed that the entities are safe if the vampire happens to stand near. (Due to the way Minecraft works this would take quite a lot of effort to prevent)

Thank you for reporting and let me know if you should face any issues regarding this with future versions

**Comment by maxanier** [comment]
There should be a new recommend build (1.3.7) shortly, please check if that actually solves this issue
