### ISSUE TITLE
sundamage_weakness_minlevel doesn't obey config changes

### ISSUE THREAD

**Issue by flamechair** [TeamLapen/Vampirism#263]
## Versions
- Minecraft:      1.12.2              
- Forge:               forge-1.12.2-14.23.1.2555-universal-server        
- Vampirism:        Vampirism-1.12-1.3.7                                     

## Issue Description
I set sundamage_weakness_minlevel=4 in vampire_player.cfg, yet Vampires on the server that are level 2 are inflicted with Weakness debuffs

## Reproduce Steps
Set  sundamage_weakness_minlevel=4
Become a level 2 Vampire
Go in sunlight
Become weak

## Additional Information
![unknown](https://user-images.githubusercontent.com/8901422/34926490-6120e400-f975-11e7-9a1c-fbcaef01df19.png)

**Comment by maxanier** [comment]
I assume the config is only changed server side?
If so, the weakness effect is only client side and should not have any effect.
Since this is rather stupid I will remove the sundamage effects on client side. This might have a small performance effect on high latency connections, but until I implement a complete config sync this is reasonable.

**Comment by maxanier** [comment]
Changed in d1a18f64f3abd986c591a9391e6021ad0d2d7f9d

**Comment by flamechair** [comment]
It was changed server side, you're right. The damage pop-off (1) might have been handled client side as well, causing it to look like it was still applying the weakness debuff
