### ISSUE TITLE
Chisel concrete doesn't block sunlight?

### ISSUE THREAD

**Issue by LemADEC** [TeamLapen/Vampirism#274]
## Versions
- Minecraft:                     1.10.2
- Forge:                       12.18.3.2511
- Vampirism:                                             1.2.4

## Issue Description
Vampires level 4+ dies when below Chisel concrete block roof

## Reproduce Steps
Using Chisel-MC1.10.2-0.1.1.39.jar (+ CTM dependencies?)
Stand below a roof using chisel concrete blocks
Be a Vampire level 1, during the day => no damage
Be a Vampire level 4, during the day => dying

## Additional Information
Other chisel blocks seems to work fine, so it might be an issue on Chisel block properties?

**Comment by maxanier** [comment]
Is the yellow screen border displayed when standing below the roof?

**Comment by LemADEC** [comment]
There's no yellow border when standing below the roof as level 1.

**Comment by maxanier** [comment]
That is weird. Can you reproduce this?
Level 1 always no damage and no yellow border.
Level 4 always damage and yellow border.

There should not be any difference between levels in the yellow border and sundamage detection  related code.

**Comment by LemADEC** [comment]
Level 1 in sunlight: I never take damage but I do get the yellow border.
Level 1 under concrete: I never take damage and never see a yellow border.

Level 11 in sunlight: I have yellow border, didn't wait for damages.
Level 11 under concrete: I have no yellow border but I get screen distortion (sometime) and get damage.

**Comment by LemADEC** [comment]
Issue isn't reproduced in single player.
I wonder if concrete block reports the same properties on server and client sides.

**Comment by maxanier** [comment]
Ok thanks for checking, I will try to reproduce and investigate this further

**Comment by maxanier** [comment]
I have tried reproducing with 1.12 and 1.10 (trying the latest chisel version), but was not able to reproduce it.
On server: Set my vampire level to 11, placed (full) red concrete blocks by chisel above me and waited. Nothing happened.

I also tried to use the chisel version specified by you, but it kept crashing when placing concrete.
Is the issue still present with newer chisel versions (0.2.*)?

**Comment by LemADEC** [comment]
We've only tested with the (bricks and cracked bricks) gray concrete blocks, not the (plain) red ones.
We're currently running with Chisel-MC1.10.2-0.2.0.43 and issue is still reproduced.
You can try using our modpack here https://www.technicpack.net/modpack/the-imperium-of-magic.1186066

**Comment by maxanier** [comment]
I am still not able to reproduce it with only Vampirism Chisel CTM (specified versions respectively).
I tried different concrete blocks including gray ones above and below sea level and nothing happened.

I also checked the Chisel source code and from the first look the block opaqueness related code (which Vampirism uses besides the height map) is fine.

So maybe a third mod is interfering. 
You could try if the issue exists also below sea level (around y60, not under water, just lower than the water) as Vampirism handles that area differently.
If the issue does not occur there it is very likely that there is an issue with height map calculation done by Minecraft which would likely be caused by a third mod.

**Comment by LemADEC** [comment]
Issue isn't reproduced with Vampirism-1.12.2-1.4.4 + Chisel-MC1.12.2-0.2.0.31. Assuming fixed
