### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by mimemister** [TeamLapen/Vampirism#292]
## Versions
- Minecraft:         1.7.10           
- Forge:                     1.7.10-10.13.4.1558  
- Vampirism:                        1.7.10-0.7.9                     

## Issue Description
Black Screen after becoming a Vampire

## Reproduce Steps
Waited twenty minutes for the effect of the bite to wear off before the screen went black

**Comment by maxanier** [comment]
Unfortunately 1.7.10 is not really supported anymore.
In addition the issue seems to be a very rare/strange one as I haven't heard anything like this in the past few years.
I guess it is either a mod incompatibility or a rare hardware/driver issue.

However, if you are really interested in getting this fixed, you could upload your full fml-client-latest.log (e.g. to paste.ee) after the screen has gone black. If I can spot anything strange in the log, there might be a quick fix.
