### ISSUE TITLE
vampire hunter cape uses textures from body

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Vampirism#324]
## Issue Description
while trying to make another texture for the "vampire_hunter_base1", i found out that the cape uses textures from the body, what maked it unpossible to make another texture.

![without extra texture for cape](https://user-images.githubusercontent.com/17816456/42465625-caa8027a-83ac-11e8-87cf-9fa2a53fecd9.png)
// without extra textures for the cape

would be nice if you can fix it.

**Comment by maxanier** [comment]
Yes, I will do that, thanks for reporting

**Comment by maxanier** [comment]
Should be fixed in next version. Cape area now starts at [x=0,y=32](https://github.com/TeamLapen/Vampirism/blob/9b38c1d54f8b6c0f154221c7ac90809e48e811ae/src/main/java/de/teamlapen/vampirism/client/model/ModelBasicHunter.java#L26-L26).
I also removed the bottom right part of the vampire_hunter_base1.png. No idea why it was there in the first place
