### ISSUE TITLE
Unable to disable version checking.

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#339]
## Versions
- Minecraft:      1.12.2              
- Forge:             forge-1.12.2-14.23.4.2750           
- Vampirism:      Vampirism-1.12.2-1.4.4.                                       

## Issue Description
update checking disabled as you can see here - 

    # Disable vampirism's version check [default: false]
    B:disable_version_check=true
}

yet, it still checks for updates every single player that logs in-
https://gist.github.com/ProsperCraft/3273afde6d52a1035596a249e0dcd51c

**Comment by maxanier** [comment]
It does not actually perform a version check.
Every time a player connects it wants to check if it should send the player a update message (if it is an admin player). However, since version checking is disabled, no version information is available, so it prints the message you can see in your logs.
You can see the source code here:
https://github.com/TeamLapen/Vampirism/blob/53475bbacccef2e0197895bede7892d821627119/src/main/java/de/teamlapen/vampirism/core/ModEventHandler.java#L89

Of course the message is a little bit misleading since the version check will never be finished. 
Might disable that log if version checking is disabled some time, but I think it is not that big an issue.

Did this help?

**Comment by ProsperCraft** [comment]
Thank you for the explanation, the log is very confusing because it would appear to be version checking.
