### ISSUE TITLE
Make vampire NPCs stronger

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#345]
The vampire mods are quite common but rather weak. Maybe it would be for "lore" friendly if they would spawn more rarely and be stronger.
The low level vampires should not be too strong, so level 0 players are not in danger too much, but we already have a leveling system for the basic vampires in place anyway so maybe the higher level ones could get a boost.
In addition it would be awesome if they could use some of the skills the player has on hand #97

**Edit**: Cheaterpaul is currently working on this here: https://github.com/Cheaterpaul/Vampirism/tree/vampire_npc

**Comment by Cheaterpaul** [comment]
do you have a link for the leveling system of the basic vampire?

**Comment by maxanier** [comment]
EntityBasicVampire implements https://github.com/TeamLapen/Vampirism/blob/1.12/src/api/java/de/teamlapen/vampirism/api/difficulty/IAdjustableLevel.java

On spawn (somewhere in ModEntityEventhandler I guess (maybe in the lib package)) the level is decided and set and this is called https://github.com/TeamLapen/Vampirism/blob/6679cc77af31d60b3779102effa804c54da1d508/src/main/java/de/teamlapen/vampirism/entity/vampire/EntityBasicVampire.java#L97

This also updates the entity attributes which vary depending on the level 
https://github.com/TeamLapen/Vampirism/blob/6679cc77af31d60b3779102effa804c54da1d508/src/main/java/de/teamlapen/vampirism/entity/vampire/EntityBasicVampire.java#L271

**Comment by Cheaterpaul** [comment]
maybe growing level stats, like the e funktion?

https://github.com/TeamLapen/Vampirism/blob/6679cc77af31d60b3779102effa804c54da1d508/src/main/java/de/teamlapen/vampirism/entity/vampire/EntityBasicVampire.java#L43

could me more?

**Comment by maxanier** [comment]
I would prefer to not increase their basic attributes too much. It is easy, but a little bit boring. A lot cooler (but also more time consuming) would be to make them use some vampire skills/actions.

Nonetheless we can increase their stats a little, to make them a little bit stronger than Zombies at least.

**Comment by shawndream** [comment]
I was going to comment here that rather than just making them stronger they should be able to summon minions behind you when angered.  (Then I found my first Vampire Baron and saw you've got that in there-ish).

I definitely think that named vamps (and Vampire Trainers) should also only have a chance every 20 seconds or so to become aggressive without being attacked (and offer trade/quests) both based on your reputation (trades vs kills) with them and blood status.

Having them be friendly and chatty until their thirst/hatred gets the better of them, would give them an interesting air of danger also... especially as they are hard to trap and respawn elsewhere (with memory)... or in the case of vampire trainiers... word gets around and mortals breed like rabbits.

**Comment by Cheaterpaul** [comment]
If I add vampir actions to the entity, should an entity be able to use all entity actions or each entity only one or a few individual actions ?

**Comment by shawndream** [comment]
Dangerous Invader Tex and Bill tending to use different skill combos seems like good texture.

They look and are named differently - acting differently seems to naturally follow.

**Comment by maxanier** [comment]
The actions should definitely be grouped by "skill level" of the vampire. So the advanced vampires should definitively have the best/most skills, as shawndream already suggested.

The basic vampires could either all have the same action or have one individual randomly chosen one (maybe based on the internal level).

**Comment by maxanier** [comment]
Closed with #378
