### ISSUE TITLE
Weird glitch and needed option 

### ISSUE THREAD

**Issue by VampyKitty** [TeamLapen/Vampirism#362]
## Versions
- Minecraft:  1.12.2                  
- Forge:  1.12.2 -14..23.4.2747             
- Vampirism: 1.12.2- 1.4.5                                            

## Issue Description:
When looking at a vampire through a window it was somehow still able to bite me and turn me into a vampire. it was a mazdallier and I'm not sure if that means if I'm in their general area i turn into a vampire but i shouldn't be turning into one if I'm inside the house. I was looking for a way to turn back to human because I'm trying to not turn into one and just survive in Minecraft but i didn't find anything so i had to turn into one which will kinda make the game harder for me. I looked for commands to remove it too but nothing for that either so it would be really nice if there was a way to stop the transformation or when you're fully turned something to turn you back. Like eating a special fruit or something. 

## Reproduce Steps: 
You'll need Minecraft comes alive and use the crystal ball and press i live alone to get a house. the house has the windows i described i was behind all you need to do is spawn the mazdallier outside the house at night nearby the window. Then just hang around the window very close to the window and it should work.

**Comment by maxanier** [comment]
Unfortunately I cannot do much about the bite through the window. It would be possible, but it would greatly increase the complexity of the code making it more buggy and more CPU heavy. Since it should only occur in rare occasions I think it is ok.

However, you can disable vampire mobs infecting you. In  the main config file (or in the MainMenu->Mods->Vampirism->Config->Disable) there should be the option "disable_mob_bite_infection" if you enable it. Mobs should not be able to actually infect you.

If you already have been infected, but did not turn yet, you can drink a milk bucket to cancel the transformation.

If you are turned already, you can look for an altar of cleansing in village churches. About every second should have one and allow you to become a normal human again.
