### ISSUE TITLE
Vampirism [1.4.9] and GuideAPI [1.12-2.1.6-61] crashing on post-init loading

### ISSUE THREAD

**Issue by IdioticRemi** [TeamLapen/Vampirism#380]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.1768
- Vampirism: 1.4.9
- GuideAPI: 1.12-2.1.6-61

## Issue Description
Game crashes at POST-INITIALIZING GuideAPI [Step 15/78]

## Reproduce Steps
Just download Vampirism, Forge and GuideAPI using Minecraft 1.12.2 and launch the game.

## Additional Information
Note I: It worked for half a day without problems but does not work anymore, I haven't changed anything.
Note II: I litterally looked after all similar issues but none of them are on the same version as I have.

## Crash report:
https://hastebin.com/gesoqikiwi.sql

**Comment by maxanier** [comment]
Unfortunately, the hastebin link does not seem to work for me (neither in Firefox nor in Chromium), it just displays an empty paste.
Can you double check that or upload it somewhere else (paste.ee, etc.)? 
Thank you.

Cannot reproduce the issue myself.

**Comment by IdioticRemi** [comment]
Sorry, it worked at first but after checking it does not so, here's the new link!
https://pastebin.com/22Bi4YUi
or (if not working):
https://0bin.net/paste/SprYjb+TWFiINCJr#dY3undQQ6MIApsfzFhYKbraytKoI1hmWBYfg55Qay6G

Thanks for helping me out.
- Kizuru

**Comment by maxanier** [comment]
I had a fix (for a related bug) ready, but accidentally did not include it yet.
Will be fixed in next releases. Until then you have to modify your `options.txt` which should be located in your `.minecraft` folder (not sure what launcher you are using).

Have a look for `key_keys.vampirism.action` (or similar). It is probably set to -97. Change it to something positive e.g. 19 before restarting Minecraft.

This changes the keybinding for the actions tab. Make sure to not set it to anything else but a standard keyboard key until the next version has been released

**Comment by maxanier** [comment]
Did that work for you?

**Comment by IdioticRemi** [comment]
Yup perfect, works again! Thank you! My keybind is apparently not being appreciated lol (Button 4)

**Comment by maxanier** [comment]
Should (hopefully) work with the next release :)
