### ISSUE TITLE
World cease functioning generating vampire forest when mowzie's mob is installed

### ISSUE THREAD

**Issue by desmfn** [TeamLapen/Vampirism#382]
## Versions
- Minecraft: 1.12.2                 
- Forge: 14.23.4.2765                      
- Vampirism:  1.4.9 and latest alpha                                          

## Issue Description
World freezes when the game try to generate vampire forest and when mowzie's mob is installed, the game didn't crush so i couldn't figure out which mod is causing the problem but the game rather freezes, also log stop generating as well. Player was able to move but all other entity freezes, as well as function such as deploying elytra during falling stopped working. It seems that only vampire forest is experiencing the issue among other mod that generate biome such as thaumcraft and abyssal craft so i think i may be posting it here.
Was using the latest stable version of mowzie's mob (1.5.2) and the few latest version all have the problem
probably mod compact issue?

## Reproduce Steps
Install Mowzie's mob mod and Vampirism mod, approaching near or one or two chunk into vampire forest. 
log will stop generating and world cease functioning however don't crush and player will still able to do basic movement

**Comment by desmfn** [comment]
In addition once attempting to save and quit the world the game will stop responding

**Comment by maxanier** [comment]
Not really sure what is causing this.
The AI of Mowzies Lanterns seems to get stuck (potentially in the collision check of the LanternMoveHandler), which causes the server thread to freeze.

The issue seems to be known to the author https://github.com/BobMowzie/MowziesMobs/issues/116
They removed the AI part of the lantern, but I think there isn't a release yet.

Until then you can probably deactivate the lanterns in the configuration of MowziesMobs
