### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Eestery** [TeamLapen/Vampirism#481]
## Versions
- Minecraft:1.7.10                    
- Forge:1.7.10                       
- Vampirism:1.7.10                                             

## Issue Description
Its the same issue that tamem313a had, My Vampirism is having problems with some ID's configuration.

## Reproduce Steps
I have Witchery and Vampirism installed, I enter in the server and its the same message, but i need to change Garlic, Sanguinare, Saturation, Thirst and Sunscreen, The problem is, I tried to re-configurate the numbers into 30-255 as you said to her, and it didnt worked, so i dont actually know what to do

**Comment by lunofe** [comment]
"1.7.10" isn't a valid version for Forge and Vampirism.

Also, keep in mind that...
> The 1.7.10 Version won't get any new features. Only major bugs will be fixed.

I don't know whether this can be considered a major bug, since there is an option to fix it yourself and I can only assume, that it worked for tamem313a (link?), meaning it's a problem on your end.

You could perhaps upload the configuration file, so someone can actually check if there is the error.

**Comment by maxanier** [comment]
As Zinalco said 1.7.10 is isn't supported anymore. (1.12 does not have IDs so issues like this cannot occur anymore.
However, it should be possible to find a working configuration. You just have to try a lot of ids
