### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by yuno44907** [TeamLapen/Vampirism#541]
2 other teams started making 2 new vampire mods because of Requiem dissolution, Howling moon doesnt work with your mode. Vampirism is a permanent curse if permanent curse is true ignore new permanent curse infections.

Also moders could make a crash fixer that will kill player tp to spawn point keep exp after death drop items and delete entities that crash or delete requests that crashing and ignore the crash also delete not working events commands entities so they dont create lag. Let say a world corrupted by werewolf vampire clash; how do you fix that player, which buff will you cancel? Lets say player becomes normal player and if event repeats latest curse will work and other curse will be removed. You can write a very short command for this stuff and admin may fix problems with gamerule commands maybe. I dont know code.

Hunters are OP. They have no debuff and strong against all monsters undeads. What about adding monks, ninjas, fighters in DnD but more balanced. You know only hunters can kill vampires and there is nothing that strong to hunter but weak to vampire. Normally Werewolves kill vampires and get murdered by hunters and hunters weak to vampires because vampires too strong fast and sneaky but werewolves, silver death.

There was spider queen mod, you could do something like that weak to fire and swims worse than player. Also vulcanite mod adds weapons that deal more damage to fire resistant mobs. Just add more monsters to game for roleplaying and there is a mod named like hardcore revival something player gets fainted when die and can be resurrected saved if other players help before he respawns or time ends. What about capturing fainted player and carying it like an item or pick up mod that lets you pick up pigs and place them top of each other create pig towers and torture cage the fainted layer like abusing and stuff. Actually i didnt test pick up mod maybe you can already pick up fainted players, but i think this mod crashes if you pick up a player.

Doesnt work with Corpse mod by henkelmax. 1.12.2 requiem mod dissolution mod ghost Remnant player gets stuck in his corpse in first death and worse, punching your corpse while you in it crashes the game because there is no data what should happen if you punch yourself. So code what happens if player punches entity he is in and is there a button for leaving the entity. Stuck only happens at first death after drinking mort potion.

 

If corpse is undead that may cause issue. Entity id of corpse must be given, what is id of corpse entity. I will disturb requiem Devs tell them do what if player punches himself and gets in an entity they dont want to be in. If Revenant leaves the corpse automaticly that solves. Stuck command maybe used i will test. Can you fix this issues if Requiem devs are dead.

 

I cant find stuck or unstuck command. I am in corpse trying to find a way to get out without crashing.

 

Corosus player zpmbie mod crashes the game after a time. Undead mod not resistant to fire immune to light, gets hungry and attacks players when hungry, can be tamed by giving meat. Runs away if hp is low. You can replace modded undeads with zombie whenever possessed by config. When player enters to whitelisted mobs that mobs become zombie.

 

Your mods never work with other transformation mods. Ghost permanent curse; if permanent curse is true immune to all other permanent curses until become player again. Basicly make transformed players to immune other transformations.

 

Option when game crashes, dont crash; kill player and tp to respawn point keep exp, items drop

**Comment by yuno44907** [comment]
Do they pay money to moders? Why dont people edit your files to fix problems with other mods? Why do people obey to rules? You know Howling Moon dev is very evil and you could edit his mod could make werewolves something like hunter and vampires cant become werewolf; you already have the code. And werewolf true command makes you werewolf so werewolf word used in howling moon mod even i can read file and find the code you need to write; yeah i think i will edit your code however i suck.

**Comment by lunofe** [comment]
Github is not the right place to write such a long commentary. Please use the [Discord](https://discord.gg/NJzT7k9) in the future.

If Vampirism is causing you any problems with other mods, please report these issues to Github as a [bug report](https://github.com/TeamLapen/Vampirism/issues/new?assignees=&labels=bug%2C+unconfirmed&template=bug_report.md&title=%5BBug%5D) with the information we require, such as the Minecraft version, Forge version, the versions of the mods involved, a detailed explanation of how the error occurred and any available logs.

If you have suggestions for the Vampirism mod that already exist in other mods (spider queen mod, vulcanite mod, hardcore revival), do not suggest them for Vampirism, just use the already existing mods.

> Hunters are OP

If you have any detailed ideas on how to change this in future versions, please submit your ideas as a [feature request](https://github.com/TeamLapen/Vampirism/issues/new?assignees=&labels=discussion%2C+enhancement%2C+feature&template=feature_request.md&title=%5BFeature%5D).

> I will disturb requiem Devs

I urge you not to do this. If developers offer the ability to suggest features or make changes for example through Github, this is a nice gesture that is not a must. Therefore, please behave yourself and be appropriate, if you ask these, but also any other developers for something.

> I cant find stuck or unstuck command

It is not the intention of the Vampirism mod to provide such functions, especially because corpses aren't part of Vampirism. If you play a modpack of a server, you could ask the administrators for such a function.

> Your mods never work with other transformation mods

The Vampirism Mod tries to deliver the best possible experience, but it is not possible to make sure in advance that absolutely every mod is compatible and properly integrated. So if you use multiple mod that have some kind of transformation, it can and probably will cause issues. 

> Do they pay money to moders?

Vampirism is currently being developed by just 2 people who also study "by the way".

> Why dont people edit your files to fix problems with other mods?

Many people already contributed to Vampirism. If the mod you want was not there, you can program a solution here on Github yourself and request it to be included in future versions of Vampirism.

> [...] you could edit his mod [...] you already have the code [...] in howling moon mod even i can read file and find the code you need to write; yeah i think i will edit your code

You should keep in mind that careless copying of works violates copyright and is only permitted under certain conditions of a license. And as mentioned earlier, if there is already a mod, do not copy its features, but work on a solution to make it compatible with Vampirism.

**Comment by yuno44907** [comment]
Make something that kills hunters but get killed by vampires like trinity or type weakness. All video games do that if they dont balance well they make it even more absurd; 4 X weak to ice.

**Comment by lunofe** [comment]
As I said, if you have detailed ideas on how to improve Vampirism, you can create a feature request. Just saying "Make something" doesn't really help when it comes to developing.
