### ISSUE TITLE
[Feature] lycanthropy aka werewolves could potentially be added considering howlingmoon is "unofficially canceled"

### ISSUE THREAD

**Issue by wolf653** [TeamLapen/Vampirism#557]
## What would you like to have changed or added to Vampirism
a new faction called Werewolves basically a human being weak to silver that turns into a melee combat specialist at night hunters could be provided with more skills and levels to deal with this type

## Does this make the mod experience more balanced?
well i guess so considering vampires are more range then melee, werewolves would be melee specialists mostly and hunters will be the bane to these factions a werewolf could considered "a vampire but without the sun torturing them and without powers at day"

## Can you provide additional resources (etc. textures or models)
sadly no as i am unable to make models and textures with a crappy computer

**Comment by lunofe** [comment]
Cheaterpaul already started working on an official werewolf add-on for Vampirism. However, it's still in very early development and:
> *Cheaterpaul:* dont get to hyped for the werewolves mod. Top One Priority is Vampirism and than i need to find time

Also, you can't just copy anything you like. Hownlingmoon belongs to razmenwolf and is liseced as follows: 
> All Rights Reserved unless otherwise explicitly stated.

It's still possible that razmenwolf could give other developers the rights to maintain their mod, but even then, I doubt that maxanier would that since he's already busy with the development of Vampirism and studying irl.
