### ISSUE TITLE
[Bug] [1.12.2] Vampire causes lag server

### ISSUE THREAD

**Issue by bigenergy** [TeamLapen/Vampirism#559]
## Versions
- Minecraft: 1.12.2                
- Forge: 14.23.5.2847               
- Vampirism: 1.5.5                                     

## Issue Description
Vampires from vampirism cause a high load on my server, after which it crashes.
Crash report: https://pastebin.com/j8t3qMJB

I profile my server using Spark profiler.
https://sparkprofiler.github.io/#oxpM06lfvl

## Reproduce Steps
No info

## Additional Information
spongeforge-1.12.2-2838-7.1.8-RC3957

**Comment by maxanier** [comment]
Did this occur once, or randomly or every time you start the server?

**Comment by bigenergy** [comment]
Randomly or when there are a lot of vampires on the server.

**Comment by bigenergy** [comment]
Any ideas?

**Comment by maxanier** [comment]
Not really, the watchdog error doesn't show anything unusual. Just some vanilla pathfinding which apparently fails to get a chunk from the chunk provider. There are many mod involved, so it is difficult to figure out which are involved.
With just Vampirism I have never seen this issue.

Does the crash always mention `at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70636_d(EntityBasicVampire.java:169)`
or can it be caused by other entities as well?
