### ISSUE TITLE
[Bug][Multiplayer]Cannot get Vampire player capability. This might break mod functionality.

### ISSUE THREAD

**Issue by dreckz** [TeamLapen/Vampirism#599]
## Versions
- Minecraft: 1.14.4                   
- Forge: 28.2.0                       
- Vampirism: 1.14.4-1.6.0-alpha+20200218-1132
--

                                            

## Issue Description
Whenever the player attempts to join the world, it ends up kicking them out. 

## Reproduce Steps
Just have player login and attempt to move

## Additional Information
https://pastebin.com/36rbfm6Y
[crash-2020-02-21_22.07.06-server.txt](https://github.com/TeamLapen/Vampirism/files/4238774/crash-2020-02-21_22.07.06-server.txt)

**Comment by maxanier** [comment]
Thank you for reporting.
The first message ("Cannot get vampire player capability ...") should not be related to any crash or player kick. That will be fixed with the next release.

Not sure about the crash report you attached, this seems to be a different issue. When exactly does the server crash with this crash log?
