### ISSUE TITLE
[Bug] Blood vision messes up rendering

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#607]

**Comment by Cheaterpaul** [comment]
still up to date?

**Comment by maxanier** [comment]
Check if the players hand is rendered correctly if using blood vision

**Comment by Cheaterpaul** [comment]
adding `GlStateManager.enableDepthTest()` after the 3 framebuffer renderExt's https://github.com/TeamLapen/Vampirism/blob/80d349b63d4cc7cfe8840e3bf6555a80e79c3d24/src/main/java/de/teamlapen/vampirism/client/render/RenderHandler.java#L442 fixes the problem.

since `Framebuffer#framebufferRenderExt` only disables the depthTest, but does not enables it.
But i know to less about that
