### ISSUE TITLE
[Feature] patchouli guidebook

### ISSUE THREAD

**Issue by lag42** [TeamLapen/Vampirism#610]
## What would you like to have changed or added to Vampirism
guide-api does not seem to be TehNut's priority at all right now last commit was 15 months ago and it was for 1.12, however patchouli is readily available and could be used for a guidebook if you're willing to use a different API

## Does this make the mod experience more balanced?
in a way i suppose, it lets new users in 1.14 and 1.15 know how the mod works

## Can you provide additional resources (etc. textures or models)
if you'd prefer not to use time on this, i could do some research on how to port the guide over myself from 1.12 and make a PR later

**Comment by maxanier** [comment]
Yes it seems unlikely that GuideAPI will be updated any time soon. I have looked into porting it myself, but that would take quite some time.

Patchouli looks like the goto alternative right no, but porting the guide will probably take quite some time as well (if we want to keep the same quality/content). Not sure when we will be able to deal with this.

If you are interested in working on a PR for this, I would greatly appreciate it. Depending on what you want to do, we could also split the work, so I do any required code changes and you port the actual content

**Comment by lag42** [comment]
sounds good, i'll start work on the json file with the actual content and let you know when it's ready

**Comment by lag42** [comment]
![2020-02-28_17 51 20](https://user-images.githubusercontent.com/22325011/75595710-12a7e580-5a53-11ea-8f17-15b166ef4044.png)
one tab done! (well, partially done if you count that i didn't link to the non-existant getting started entries for both classes)
here's a zip of what i've done so far, fresh from json hell, the rest of the tabs will get done as soon as i can get them done
[vampirismguidebook.zip](https://github.com/TeamLapen/Vampirism/files/4269631/vampirismguidebook.zip)

**Comment by lag42** [comment]
![2020-02-28_17 51 20](https://user-images.githubusercontent.com/22325011/75595914-e17be500-5a53-11ea-9a01-c8958fb63270.png)
one tab done! (well partially done if you count the fact that i didn't link to the as of yet non-existent getting started entries for both classes)

here's a zip of what i've done so far, the rest of the tabs will be done as soon as i can get them done
[vampirismguidebook.zip](https://github.com/TeamLapen/Vampirism/files/4269655/vampirismguidebook.zip)

**Comment by maxanier** [comment]
Awesome, thank you :)
I have started working on the recipe pages for weapon table etc.
But I will also have to look how to integrate the crowdin translations here. I want to avoid requiring everything to be translated again.
Additionally I will have to figure out how to integrate values from the mod into the guide book. So that if some values change in the mod, the guide book does not have to be updated manually.

So it would probably best, if you wait with further work until I am done with that

**Comment by lag42** [comment]
if you could also make a better way of displaying the table on the leveling pages that would be great, i already tried to write out all of vampire before you said that and i couldn't find a good format

but thank you for all the work on the mod so far, what i'm doing is really only a fraction of that at best and i hope it helps at least a little

**Comment by maxanier** [comment]
Just an update. I haven't had enough time to properly deal with this yet.
Weapon table recipes are working now and the translation issue can be solved by just using translation keys instead of the actual text in the entries.

However, two issues remain. Firstly replacing parts of the text with values from the mod (so they are always up-to-date and in sync with the used configuration) isn't that convenient. Secondly, text does not automatically wrap around pages, which a) means the translations will have to be split up into multiple keys and b) can cause issues with the translations itself as some languages tend to produce longer texts than the English original.

I will let you know, once I found a solution

**Comment by lag42** [comment]
guide-API-VP seems to solve everything here

**Comment by maxanier** [comment]
Yeah, sorry.

After some more consideration, I decided it would be easier to port Guide-API than to rewrite the guidebook and possibly require a complete retranslation.

Thank you for your work anyway :)
