### ISSUE TITLE
Pure Blood 5/5

### ISSUE THREAD

**Issue by r1e2x310** [TeamLapen/Vampirism#62]
I know that you kill each level of vampire lord to get each level of pure blood. but I have never even seen a level 5 vampire. Is this the way you get 5/5 pure blood. And also, do lords spawn at a random level or do they level up by killing other lords or by any other means?

**Comment by maxanier** [comment]
Since you already closed the issue, I guess you have found one?

The level of a spawning vampire barons is calculated under consideration of the level of near vampire players. If you are on a level at which you need a pure blood 5, level 5 barons should spawn most commonly. Barons of another level still might spawn, but with a lower chance.

**Comment by r1e2x310** [comment]
Yes, once I got to LVL 13 they were everywhere. Sorry for being impatient and starting a thread. I am now a happy vampire lord. =)
