### ISSUE TITLE
[1.9] java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=part, clazz=class de.teamlapen.vampirism.blocks.BlockCoffin$EnumPartType, values=[head, foot]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

### ISSUE THREAD

**Issue by squirrelkiller** [TeamLapen/Vampirism#67]
I feel so bad to give you one crash right after you released a fix for another, but when you do youtube you tend to put in the hours ASAP after waiting on a patch, so naturally you tend to see issues. On the brightside once this is more stable I am really tempted to do an indepth tutorial series on it

Crash report, this hit out of nowhere I was just clearing a path for a train system:
[crash-2016-04-28_16.34.00-client.txt](https://github.com/TeamLapen/Vampirism/files/241406/crash-2016-04-28_16.34.00-client.txt)

**Comment by maxanier** [comment]
Don't worry, I'm glad that you are reporting so many issues (even thought that means, there actually are bugs in Vampirism ;) ).
This is the only way, I can get rid of them.

I'm not totally sure what the root cause of this is, but I've released a fix  (at [curseforge](http://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files)) that should prevent this. 

Do you remember if there were any coffins around you or did you break one when the crash occurred?

> I am really tempted to do an indepth tutorial series on it 

Sounds great, contact me on the Minecraft Forum, if you start and need any help or additional information.

**Comment by squirrelkiller** [comment]
I was maybe 3-4 chunks away from one when I started, I was digging, Load Distance was 5 chunks because recording is nasty on performance, adding it all up I have two theories, either A) it only just loaded in and crash, or B) it unloaded and it crashed, or C) (and I would need to check this) it was placed across a chunk boundary and it crash because of something related to that, which is not unheard of. Chunks are the main reason I have everything break on me.

**Comment by squirrelkiller** [comment]
I have confirmed that is was caused by it unloading, so that might be an issue with other blocks if you repeat whatever you did before.

**Comment by maxanier** [comment]
Thanks for testing this, I will take a second look if I can find the root cause
