### ISSUE TITLE
<Insert catchy Milk slogan here>

### ISSUE THREAD

**Issue by Parapetenia** [TeamLapen/Vampirism#688]
## Versions
- Minecraft: 1.15.2                    
- Forge:  1.15.2 - 31.1.87                      
- Vampirism:  Vampirism-1.15.2-1.6.0-beta.1                                           

## Issue Description
You can cure Sanguinare Vampiris by simply drinking milk. 

## Reproduce Steps
Contract Sanguinare Vampiris.
Drink milk.
All better.

## Additional Information
Nothing more, just figured it might have been overlooked.

**Comment by maxanier** [comment]
This is intentional.
It probably does not make much sense lore wise, but we need a way for players to get rid of the effect if they get infected by accident (especially in a larger modpack).
Since the milk bucket is the MC way of getting rid of effects, this is the most intuitive way I hope.

We could add a config option to disable this, but I don't think anyone would use it

**Comment by Parapetenia** [comment]
I just realized that actually.  There is a config for it in the serverconfig file that is created upon world creation, canCancelSanguinare = true. I'll just turn it off.  Thank you for the quick response.

**Comment by maxanier** [comment]
Didn't know we already had that option :see_no_evil: :D
