### ISSUE TITLE
Glowing vampire eyes/Personalised Vampires

### ISSUE THREAD

**Issue by EpicCreeperHD** [TeamLapen/Vampirism#72]
I'm loving this mod so far! Playing as a vampire on my modded server is one of the best things and recently I've had my Vampire Lord status challenged and I'm now in the midst of a clan war. The thing that's been stopping the pair of us from making this feel and look as badass as it sounds is the following;
- All vampire players use the same texture for when they've turned which, obviously, will not work on all skins. I understand that in 1.9 you can adjust this to your skin with commands, but imagine things like your skin becoming paler and perhaps even an entirely different look as a vampire. We've overcome this by disabling them on the server and customising our actual skins, but it's a nuisance when we log onto other servers and change back. We'd like to suggest a system where a user places a skin texture in their game directory and that is used as their vampire appearance instead of a generic texture.
- Vampire minions are enslaved identical children. Why? I can understand the whole skin thing to identify their masters but why are they children/midgets? It would make more sense if the player created their own texture, placed it (or a folder) in their directory and have that (or a random one from the folder) used instead of their own skin. It means that when you declare war, it's not ridiculus looking.
- Seperate the eye textures on vampire players from the fangs. Why? Glowing eyes! Of course, optional but it would be interesting for vampires' eyes to glow in the dark while using night vision. Just imagine that one player who's got himself lost at night seeing those eyes in the dark.

**Comment by maxanier** [comment]
Thanks for this extensive feedback.
The main problem with skins/textures is that they should be available for all clients. Minecraft itself does this for the skins via the official skin servers.  
For syncing custom vampire skins/overlays or minion textures I would have to either setup my own server or use some kind of user controlled system, but the first is too time consuming and expensive and the second one to insecure.
But there are two alternatives: 
1. You could create a resource pack which replaces the /entitiy/vanilla/steve* textures and one player uses e.g. eye type 2 and the other eye type 3. 
2. I'm willing to add more overlays to vampirism which would then be available to all players by default. If you send me an overlay (64x64, transparent background, see e.g. [this](https://github.com/TeamLapen/Vampirism/blob/86f04ef6afb59e23648dca32d725a789171ec8a8/src/main/resources/assets/vampirism/textures/entity/vanilla/steve1.png)) and it looks acceptable, I will add it.

About separating the eye texture from the fangs: Sounds good, I will do that at some point. The glowing eyes: Maybe, since it's probably not very easy to add.
I will also think about the minions again.

P.S. All of the above is about Mc 1.9, the 1.7.10 version of Vampirism won't be updated anymore.

**Comment by EpicCreeperHD** [comment]
> About separating the eye texture from the fangs: Sounds good, I will do that at some point. The glowing eyes: Maybe, since it's probably not very easy to add.
I will also think about the minions again.

Glad to hear! It could also allow you to make a vampire's mouth bloody after feeding if you so desired.
I see you're a bit stuck thinking of ideas for becoming a vampire hunter. The idea you got with the whole studying vampires thing works great, but should be how you get introduced to it. After you've researched all you can and built yourself your gear you should then be prompted to learn and disrupt vampire hierarchy to level up i.e. Find vampire bosses and kill them ending with the vampire lord, which could be an interesting reason for hunters to go into all out war with vampires.
Another idea could be silver weapons which do extra damage to the undead and the ability to recruit villagers into vampire hunters like the vampire lord can with his minions.
I have no idea how difficult that would be to actually get functioning, but it's at least an idea of where to go hopefully.

**Comment by EpicCreeperHD** [comment]
I found the code for rendering Spiders and tweaked it a bit to perhaps work in this context. I'd like to try adding it into your code, but theres a lot to read through and I'm short for time right now. If you haven't already once I get the time, I'll see if I can implement the texture-related things for you.

Obviously, you can change the texture to whatever the variable that holds the user's vampire eye texture there.

I doubt this works, but I'll find out once I get the time to test it.

```
protected boolean setVampireEyeBrightness(EntityPlayer vampireplayer, int i, float f)
{
if(i != 0)
{
return false;
}
if(i != 0)
{
return false;
} else
{
loadTexture("/enitity/vanilla/steve1.png");
float f1 = (1.0F - vampireplayer.getEntityBrightness(1.0F)) * 0.5F;
GL11.glEnable(3042 /*GL_BLEND*/);
GL11.glDisable(3008 /*GL_ALPHA_TEST*/);
GL11.glBlendFunc(770, 771);
GL11.glColor4f(1.0F, 1.0F, 1.0F, f1);
return true;
}
}
```

**Comment by Nichiatu** [comment]
why are you checking if i is 0 twice?

**Comment by maxanier** [comment]
I didn't know/remember that the vanilla spider eyes are already glowing.
I took a short look at the vanilla code (net.minecraft.client.renderer.entity.layers.LayerSpiderEyes) which looks a little bit different from yours and messes with the lightmap.
Maybe yours is for MC 1.7.10?

Anyway since it does not look too time consuming I will implement that at some point soon.

**Comment by maxanier** [comment]
Fangs and eyes are now separated and can be set with "/vampirism eye <id>" and "/vampirism fang <id>". It now is also possible to choose a clear overlay, so skins which look like someone is a robot or so aren't messed up.
Other players can still recognize them by the color of their nametag.

Glowing eyes are possible, but there still are a few problems, so I've postponed that feature

**Comment by Vavency** [comment]
How hard would it be to change overlay position?

**Comment by maxanier** [comment]
Of the eyes?

Depends if you want to see that change only yourself or if everybody on a multiplayer server should see it.

For the first you would just have to create a resource pack overriding https://github.com/TeamLapen/Vampirism/blob/1.12/src/main/resources/assets/vampirism/textures/entity/vanilla/eyes0.png.

For the latter I would have to include the modified texture in the mod.

However, a code based solution, allowing a configurable offset to the rendering of the overlay might be possible too

**Comment by Vavency** [comment]
If you're feeling lazy and up for some bodging, modified textures look like a quick and easy solution.

**Comment by Vavency** [comment]
[vamp_aye.tar.gz](https://github.com/TeamLapen/Vampirism/files/1169120/vamp_aye.tar.gz) Here you go.

**Comment by maxanier** [comment]
Thx, will add them sometime

**Comment by maxanier** [comment]
Sorry I think I forget this at some point.

Regarding the glowing eyes, just implemented something similar for a halloween special 4df4a4885318a240ee9526984868f64093448ec0, looks like it would not be to hard to add this to players too.

**Comment by maxanier** [comment]
Added a few more (shifted) eye types.
Also added glowing eyes finally (disable with /vampirism glowingEyes false)

Both are non optimal solutions:
- The eye types could be easier (and more dynamically) configurable
- The glowing eyes also make the black parts of the eye glow white

However, don't want to spend too many hours on this feature
