### ISSUE TITLE
[Bug] [1.16] Hunter tent distance

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#737]

**Comment by Cheaterpaul** [comment]
We are adding all relevant StructureSeparationSettings in `ModFeatures#registerStructures` to  `DimensionStructuresSettings#field_236191_b_` which is right, but because of the static context the field was already used for the dimension structure settings before forge calls the mod constructors. Which means we can not do anything except maybe a core mod.

**Comment by maxanier** [comment]
So just hacking a put with the hunter_camp settings should suffice, right?
Modifying the village size won't be possible with this, but that shouldn't be too important for now I guess.

**Comment by Cheaterpaul** [comment]
yes that would suffice

**Comment by maxanier** [comment]
Instead of coremod, I just modified the overworld preset now. Appears to be working fine even though the settings are not added to the static map now
