### ISSUE TITLE
Make sure Vampirism gear can compete with Netherite gear

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#785]
With the new weapon/armor tier of netherite (above diamon) we should make sure that Vampirism's weapons/armor can compete with these. This might require bumping the stats or adding new tiers/types.

**Comment by Cheaterpaul** [comment]
In terms of hunter armor we could
- duplicate the obsidian armor into netherite armor (add netherite armor of hell with 3 tiers)
  - either by replacing obsidian in the recipe
  - or as an upgrade of the obsidian ones
- adding 2 extra tiers, so that all are up-gradable (last not craftable)

**Comment by Cheaterpaul** [comment]
In terms of vampire swords we could
- do the same as the armor ^^
- add some magic ritual? to enhance the weapon

**Comment by maxanier** [comment]
Ok, after putting some more thought into this I am still not sure what to do.
Currently Vampirism's gear can compete very well with Netherite stuff.
The vampire swords deal the same amount or more damage already (although they require training etc..)
The obsidian armor provides more or the same amount of protection.
There isn't a hunter sword. The axe is special anyway.

In general we want to offer better items than Vanilla has (at a higher cost). It seems that is still the case.
Also if we want to make to make the swords and obsidian armor upgradeable, this would mean 18 new items.

**Comment by Marsmalo** [comment]
I don't know if I can post here but I need to say this: Vampire Swords only in their Ultimate Form is able to compete with a Netherite Sword with Sharpness 5. But if you have a Netherite Sword with Sharpness 5 and you're a Hunter and uses the Swift as the Wind, you get MORE DPS and thus making a Sword that the vampires need to grind for (looking hours for Vampire Dungeons) be like something useless and thus making no sense to grind for them because if you die for a Hunter you'll probably lose everything. 
You could make the Sword be enchanted with every single enchant that we can put in a normal Sword to bring more damage for the Vampires when they get the Ultimate and Enhanced from Vampire Dungeons or other treasure chests in the world. This is really balancing, only the people who really wanna be strong and compete in PvP or Wars will have them because they will go out and search for them. **Making the Ultimate Swords really OP but they are really hard to find** is the best option after talking to a lot of vampire and Hunter players.

**Comment by maxanier** [comment]
Rebalanced in b22d3eaaaef1aa902e54aea69728ed8a225a5dcd
