### ISSUE TITLE
Add biteable creature[Bug]

### ISSUE THREAD

**Issue by icehandler** [TeamLapen/Vampirism#807]
## Versions
- Minecraft: 1.16.3                   
- Forge: 34.1.42                      
- Vampirism: 1.6.1                                            

- ModPack: N/A

## Issue Description

Hello, I added a new biteable creature from the mod minecolonies, following the instructions on the wiki.
I openned the vampirism.jar file and in : 
/data/vampirism/vampirism_blood_values/entities/ 
I added a new file minecolonies.txt
In this file, I wrote this :
minecolonies:citizen=15

There is no probleme while lauching the game and the citizen of minecolonies had the red cursor that make them biteable.
BUT
When I want to bite them, their take damage like if I pressed one time the key. I can't drink their blood like other creature.
The red cursor is there but citizen are hited like non-biteable creature.

Is it normal because I failed something ? Or is it a bug ?

I also tryed with chicken in the minecraft.txt file, beacause I know the default value is 0 but the same thing happened.

Sorry for my mistakes in english and thanks for reading.

Ice handler

**Comment by maxanier** [comment]
Putting directly in the jar is a rather unusual approach, usually you would want to create a datapack. I am not entirely sure if it can work this way.

If you are doing this on a server, make sure to edit it both on server and client side.

Otherwise create a datapack:
https://github.com/TeamLapen/VampirismDatapackExamples/tree/1.14/bloodvaluespack
https://minecraft.gamepedia.com/Tutorials/Creating_a_data_pack

I double checked it, and it is working

**Comment by icehandler** [comment]
Ok I will try with a datapack.
Thanks for this answer.
