### ISSUE TITLE
[Feature] Change the Totem beam visibility

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Vampirism#874]
## What would you like to have changed or added to Vampirism
Change the Totem beam rendering in a way, that it does not always is a giant beam in the sky.

eg. only render the beam while capturing and using a name plate to show the faction

Source:

> Oh man, that's what I was afraid of.  I'm kind of trying to center things around exploration, and having a big giant beam in the sky kinda kills the 'I discovered a village' excitement.

>That's a hard one.  To be honest, i've never felt like I needed to know who controls the village when outside the village.  I do feel like it would be weird to have a beam to the sky just suddenly pop into the sky when you're about a chunk away.
Off the top of my head, something generally more localized?  Particle effects, a banner, something a bit smaller?
Or maybe just some way to make the beacon only active when it's being utilized in some fashion?

>I think a Beacon is the best way to have the whole capturing thing, but maybe we keep the beacon but it doesn’t activate until it is taken by Vampires or Vampire hunters like what Aquifel said.  So we find villages normally, and can find them again easily, and have the same beacon affect so it looks great

## Does this make the mod experience more balanced?
This results in a better experience while traveling/exploring the world

**Comment by Suraru** [comment]
+1, based on the status I assume it's been added, but turning off the skybeam is basically all I want. I saw on the forums you were considering banners instead of totems, which would be much more immersive. 

Might be a bit out of scope, but compatibility with FTB chunks, or Serilum's Area mod to add-on to the title cards, or maybe it's own title card displaying the controlling faction (With of course, a setting to turn it off). HWYLA tooltip compat with the totem displaying faction would also be nice.

**Comment by Cheaterpaul** [comment]
yes the beam will be turned of while there is no capturing in progress instead a name tag is rendered over the totem
