### ISSUE TITLE
Craftable Tent

### ISSUE THREAD

**Issue by halk6000** [TeamLapen/Vampirism#882]
hi i have simple ideas to great expirience whtch this mod. add craftings for tent of hunters when you need ? you need normal tent recipe three stick for tent frame  up mid, left and right the middle of the side if you have tent frame so your need 6 x carpet of any wool. 
![idea](https://user-images.githubusercontent.com/45394417/111870566-c2fdca00-8985-11eb-93f7-2de87da68914.png)
hmm and add mayble can you dring vampire hunter xD he is human xd but you have 15 % + confiruable if when you dring this hunter you get withering effect for 4 s black hearth. 
add book named ,, how to be a vampire " you get this book when you frist time get  poison from vampire, ,, when start turn you for vampire" or when you kill vampire frist time. this typical tutorial for this mod ;) 
add when you have mca can you talk from another vampire when you a vampire. this interactions start when you kiss vampire xD   yea when you try dring blood :)  but you nothing blood is a vampire ,gives you little quests when you done you get nonfiltred blood bottle. another interactions is challange vampire is normal fight but you must lot or missions done if this vampire have more rank tham you so win this fight get your one points for stats vampire. ;) 
+ i dont good for pixelart so if want i can tralnslate this mini mod for polish.

**Comment by lunofe** [comment]
Thank you for your suggestions. I don't mean to be rude, but I only understood half of it. I think it would be easier if you first write your ideas completely in Polish and then translate it with [Google Translate](https://translate.google.com/) or [DeepL](https://www.deepl.com/translator) to English.

**Comment by halk6000** [comment]
ok sorry english is not my native . that's why I tried to paste the drawings so you can see what's going on. I think the drawings are legible. 

so
- frist name tent frame - new item your need to craft tent 
- secoundary - in the picture add craft for normal tent 
- third - in the picture add crafting hunter tent. 
- fourth a few reactions to your vampire style of play. when you have mca. you can talk anorher vampire when if you're a vampire too. greeting them is a bite, use bite to another vampire to start interactions. get tiny quests when end you get from him a bottle of unfiltered blood , when you fill the reputation bar of this vampire properly, you will be able to challenge him to a duel. when his rank is higher than yours, you will get 1 point to spend.
- fifth thing to be able to drink hunter's blood, but by default you have a low chance of 15% that you will get the withering effect for 4s. is configurable 
- 6 optional make it possible to create a potion of fire resistance + refined obsidian dust from the mekanism mod. this gives a sun resistance mixture for 4 minutes extended to 6 minutes when you add redstone powder to it.

**Comment by Cheaterpaul** [comment]
# 1/2

Making the tent craft-able seems fine as decorative block or bed.

# 3
Making mob spawner will not be considered. Vanilla has no craft-able spawner for their mobs so do we. Other mods are free to add craft-able spawner

# 4
This seems like a nice idea that we can think about, but it will most likely never implemented due to time limitations and the orientation of the mod

# 5
Currently we follow the path that hunters are save from vampire bites, due to our lore

# 6
Sun immunity is a no-go in our philosophy. Vampires are simply vulnerable to the sun. We supply a limited sun screen action which at least makes it not so hard to walk at day, but we do not intend to change that. If you want to negate the sun weakness you can use third party mods like Vampires needs Umbrellas or enable the build-in umbrella which you need to activate in the config options
