### ISSUE TITLE
[Bug] there are the right amount of skill points 

### ISSUE THREAD

**Issue by noir2099** [TeamLapen/Vampirism#968]
## Versions

- Minecraft: 
- Forge: 1.16.5
- Vampirism: 1.16.5

- ModPack: N/A

## Issue Description
can you have it to be that you can get more skill point so that you can get every skill somehow? i fell it just a little annoying to not be able to get all of them

## Additional Information
please add more skill point so you can get all upgrades

**Comment by maxanier** [comment]
This is absolutly intentional.
There is a (cheat) config that allows you to either unlock all skills at max level or to get more points per level.
Config: https://github.com/TeamLapen/Vampirism/wiki/Configuration
Alternatively you can install GodlyVampirism: https://www.curseforge.com/minecraft/mc-mods/godly-vampirism
