### ISSUE TITLE
[Feature] Configure Angry Villager health or disable them

### ISSUE THREAD

**Issue by Lerrycapetime** [TeamLapen/Vampirism#978]
## What would you like to have changed or added to Vampirism

I have the guard mod currently installed so I feel this makes gameplay more balanced. Hopefully we can disable or increase health of angry villagers in the config. I'm tired of my top tier villagers dying quickly from powerful vampires. Another note is that vampires count as passive towards guards until they attack a villager, so that's kind of strange. Anyways thank you for reading.

**Comment by Cheaterpaul** [comment]
The villager guards can be disabled in the next release by changing the `disableVillageGuards` in the server config to true.

The hostility towards vampires is probably caused by the fact that they are not declared as Monster. But changing things about that would cause the guards to attack vampires even if it is a vampire village. Trying incorporate the guards into vampirism logic would require some mod compatibility. If you would like more compatibility please create an issue here https://github.com/TeamLapen/VampirismIntegrations/issues
